name: Manually triggered workflow
on:
  repository_dispatch:
  
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Set dev version env
        shell: bash
        env:
          envs: ${{ toJson(github.event.client_payload.env) }}
        run: |
          echo $envs
          echo $envs | jq -c '.[] | contains("QA-FEATURE")'
          if $envs | jq -c '.[] | contains("QA-FEATURE")' > /dev/null; then
            echo "BUILD_VERSION=$(date +"%Y.%m.%d.%M%S-feature")" >> $GITHUB_ENV
          else
            echo "BUILD_VERSION=$(date +"%Y.%m.%d.%M%S-${{ github.event.client_payload.branch }}")" >> $GITHUB_ENV
          fi
      - name: Set dev version env
        shell: bash
        run: echo "${{ env.BUILD_VERSION }}"
