name: Manually triggered workflow
on:
  repository_dispatch:
  
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: get arr length
        id: getenvlength
        env:
          envs: ${{ toJson(github.event.client_payload.env) }}
        run: |
           echo "$envs"
           LL=$(echo $envs | jq '. | length')
           echo "::set-output name=environments::$LL"
      - name: Run if two environments
        if: steps.getenvlength.outputs.environments == 2
        run: |
          echo "${{github.event.client_payload.env[0]}}
          echo "${{github.event.client_payload.env[1]}}
      - name: Run if only one environment
        if: steps.getenvlength.outputs.environments == 1
        run: |
          echo "${{github.event.client_payload.env[0]}}
          echo "${{github.event.client_payload.env[1]}}
