name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      arrWithTwo:
        description: 'Two length array'
        required: true
        default: ['TEST', 'TEST1']
      arrWithOne:
        description: 'One length array'
        required: false
        default: ['TEST']


      #arrWithTwo: ['TEST', 'TEST1']
      #arrWithOne: ['TEST']
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run this if index 1 is not null
        if: ${{github.event.inputs.arrWithTwo[1] != null }}
        run: echo "FOUND index 1!"
      - name: Run this if index 1 is null
        if: ${{ github.event.inputs.arrWithTwo[1] == null }}
        run: echo "DID NOT FIND index 1!"
