name: Manually triggered workflow
on:
  repository_dispatch:
  
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Set dev version env
        if: github.event.client_payload.branch != 'master'
        shell: bash
        env:
          envs: ${{ toJson(github.event.client_payload.env) }}
        run: |
          echo $envs
          ISFEATURE=$($envs | jq -c '.[] | contains("QA-FEATURE")')
          echo $ISFEATURE
          if [[ $ISFEATURE = "true" ]]
          then
            echo "BUILD_VERSION=$(date +"%Y.%m.%d.%M%S-feature")" >> $GITHUB_ENV
          else
            echo "BUILD_VERSION=$(date +"%Y.%m.%d.%M%S-${{ github.event.client_payload.branch }}")" >> $GITHUB_ENV
          fi
          echo ${{env.BUILD_VERSION}}
