name: Manually triggered workflow
on:
  repository_dispatch:
  
jobs:
  say_hello:
    env:
      working-directory: ./
      frontend-dir: ./frontend
      backend-dir: ./backend/backend/IvoRegister.EService
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      ICON_URL: https://avatars.slack-edge.com/2020-04-29/1092826931749_6ccbae7250fb01b99dda_192.png
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Actions Slack integration
        uses: meridium/slack@v1.2.9-bulkbogan-test
        with:
          status: starting
          channel: '#bot-test'
          username: 'Bulk Bogan'
          iconUrl: ${{env.ICON_URL}}
          octopusChannel: ${{ github.event.client_payload.channel }}
          octopusEnv: "${{ github.event.client_payload.frontendEnv }} and ${{ github.event.client_payload.backendEnv }}"
          startedBy: ${{ github.event.client_payload.user }}
          skipDeploy: ${{ github.event.client_payload.skipDeploy }}
      - name: Test deploy
        if: github.event.client_payload.skipDeploy != 'true'
        shell: bash
        run: echo "Deploying"
      - name: Test not deploy
        if: github.event.client_payload.skipDeploy != 'false'
        shell: bash
        run: echo "Skipping deployment"
